# Generated by Django 4.2.11 on 2024-10-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbiblioteca', '0002_alter_autor_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='rol',
            new_name='nombre_rol',
        ),
    ]
