# Generated by Django 4.2.11 on 2024-10-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbiblioteca', '0003_rename_rol_rol_nombre_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(max_length=500),
        ),
    ]
