# Generated by Django 4.2.11 on 2024-10-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbiblioteca', '0004_alter_autor_biografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(max_length=600),
        ),
    ]
